# Generated by Django 6.0.2 on 2026-06-27 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('avatar', models.CharField(blank=True, max_length=10, verbose_name='Initiales Avatar')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Est bloqué')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note interne')),
            ],
            options={
                'verbose_name': "Utilisateur de l'application",
                'verbose_name_plural': "Utilisateurs de l'application",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='MadaBot Assistant', max_length=30)),
                ('welcome_message', models.CharField(default='Bonjour ! Je suis votre assistant virtuel. Comment puis-je vous aider aujourd’hui ?', max_length=160)),
                ('selected_color', models.CharField(default='#10B981', max_length=7)),
                ('selected_avatar', models.CharField(default='🤖', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Fanomezantsoa Rado', max_length=150)),
                ('user_email', models.EmailField(default='rado.andrinaivo@email.com', max_length=254, unique=True)),
                ('selected_language', models.CharField(default='Français', max_length=50)),
                ('is_two_factor_auth', models.BooleanField(default=True)),
                ('is_push_notify', models.BooleanField(default=True)),
                ('is_email_notify', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('escalated', 'Escalated to human')], default='active', max_length=20)),
                ('converted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('conversations_count', models.PositiveIntegerField(default=0)),
                ('converted_count', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('unique_active_users', models.PositiveIntegerField(default=0)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='api.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_interaction', models.CharField(max_length=50, verbose_name='Type (FAQ, Support, Spam...)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'interaction")),
                ('summary', models.TextField(verbose_name="Résumé de l'interaction")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.appuser', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('ai', 'AI Node'), ('agent', 'Human Agent')], max_length=10)),
                ('content', models.TextField()),
                ('node_id', models.CharField(blank=True, max_length=120, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User/Visitor'), ('bot', 'Chatbot')], default='user', max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.chatbot')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.conversation')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['chatbot', 'started_at'], name='api_convers_chatbot_cbef93_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['chatbot', 'date'], name='api_dailyme_chatbot_43a5ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetric',
            unique_together={('chatbot', 'date')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='api_message_convers_ece45b_idx'),
        ),
    ]
